WebPortal/Models/sale.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sale()
        {
            this.gratuities = new HashSet<gratuity>();
            this.payments = new HashSet<payment>();
            this.salesitems = new HashSet<salesitem>();
        }
    
        public int id { get; set; }
        public int userid { get; set; }
        public int ticketno { get; set; }
        public Nullable<int> customerid { get; set; }
        public Nullable<System.DateTime> saledate { get; set; }
        public Nullable<System.DateTime> lastupdated { get; set; }
        public Nullable<decimal> adjustment { get; set; }
        public string status { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public string note { get; set; }
        public Nullable<int> employeeid { get; set; }
        public string custom1 { get; set; }
        public string custom2 { get; set; }
        public string custom3 { get; set; }
        public string custom4 { get; set; }
        public Nullable<int> rewardexception { get; set; }
        public Nullable<int> stationno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gratuity> gratuities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment> payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salesitem> salesitems { get; set; }
    }
}

WebPortal/Controllers/SalesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAccess.Models;
using WebAccess.Helper;
using System.Data.Entity;
using WebAccess.ViewModels;

namespace WebAccess.Controllers
{
    public class SalesController : BaseController
    {
  
        // GET: Sales


        public ActionResult Index(int? reporttype, int? StoreId, string startdate, string enddate)
        {

            int webid = 0;

            if (startdate == null) startdate = DateTime.Now.ToShortDateString();
            if (enddate == null) enddate = DateTime.Now.ToShortDateString();

           
            ViewBag.SalesType = SelectListHelper.GetUserStores(CurrentUser, reporttype);
            ViewBag.startdate = startdate;
            ViewBag.enddate = enddate;

            DateTime StartDate = Convert.ToDateTime(startdate);
            DateTime EndDate = Convert.ToDateTime(enddate);

            var defaultstore = CurrentUser.stores.FirstOrDefault();

            if (defaultstore != null)
            {

                if (StoreId.HasValue)
                {
                    webid = (int)wa.stores.Find(StoreId).WebUserId;
                    ViewBag.Stores = SelectListHelper.GetUserStores(CurrentUser, StoreId);
                }
                else
                {
                    webid = (int)defaultstore.WebUserId;
                    ViewBag.Stores = SelectListHelper.GetUserStores(CurrentUser, defaultstore.id);
                }

              /*  var sales = (from s in context.sales
                             join empsub in (from emp in context.employees where emp.userid == webid select emp) on s.employeeid equals empsub.employeeid into ps from c in ps.DefaultIfEmpty()
                             join t in context.salesitems on s.id equals t.salesid
                             join e in context.employees on t.employeeid equals e.employeeid
                             where s.userid == webid && e.userid == webid
                             && DbFunctions.TruncateTime(s.saledate) >= DbFunctions.TruncateTime(StartDate)
                             && DbFunctions.TruncateTime(s.saledate) <= DbFunctions.TruncateTime(EndDate)
                             group new { s, t, e } by new { s.id, s.saledate, c.firstname, c.lastname, s.ticketno, s.total, s.subtotal, s.status, s.note, s.adjustment, s.custom1, s.custom2, s.custom3, s.custom4, s.payments, s.gratuities } into g
                             select new Ticket
                             {
                                 id = g.Key.id,
                                 saledate = g.Key.saledate,
                                 EmployeeName = g.Key.firstname + " " + g.Key.lastname,
                                 ticketno = g.Key.ticketno,
                                 total = g.Key.total,
                                 subtotal = g.Key.subtotal,
                                 status = g.Key.status,
                                 note = g.Key.note,
                                 adjustment = g.Key.adjustment,
                                 custom1 = g.Key.custom1,
                                 custom2 = g.Key.custom2,
                                 custom3 = g.Key.custom3,
                                 custom4 = g.Key.custom4,
                                 payments = g.Key.payments,
                                 gratuities = g.Key.gratuities,
                                 TicketItems = g.Select(x => new TicketItem {EmployeeName = x.e.firstname,quantity = x.t.quantity,description = x.t.description, price = x.t.price, discount = x.t.discount, note = x.t.note })
                            
                               
                             }).ToList();

                */

                 var sales = (from s in context.sales 
                              where s.userid == webid 
                              &&  DbFunctions.TruncateTime(s.saledate) >= DbFunctions.TruncateTime(StartDate)
                             && DbFunctions.TruncateTime(s.saledate) <= DbFunctions.TruncateTime(EndDate)
                              select s).ToList();


                    return View(sales);
                
            }else
            {
                
                return View("NoStores");
            }
           
               
           
           
        }



        // GET: Sales/Details/5
        public ActionResult Details(int id)
        {
            var sales = context.sales.Find(id);
            int webid = sales.userid;


            var detail = (from s in context.sales
                          join empsub in (from emp in context.employees where emp.userid == webid select emp) on s.employeeid equals empsub.employeeid into ps
                          from c in ps.DefaultIfEmpty()

                          where s.id == id
                          select new Ticket
                          {
                              id = s.id,
                              userid = s.userid,
                              ticketno = s.ticketno,
                              saledate = s.saledate,
                              subtotal = s.subtotal,
                              adjustment = s.adjustment,
                              total = s.total,
                              note = s.note,
                              custom1 = s.custom1,
                              custom2 = s.custom2,
                              custom3 = s.custom3,
                              custom4 = s.custom4,
                              status = s.status,
                              stationno = s.stationno,
                              gratuities = s.gratuities,
                              payments = s.payments,
                              EmployeeName = c.firstname + " " + c.lastname
                            
                         }).FirstOrDefault();

            detail.TicketItems = (from t in context.salesitems
                                  join e in context.employees
                                  on t.employeeid equals e.employeeid
                                  where e.userid == detail.userid && t.salesid == detail.id
                                  select new TicketItem
                                  {
                                      id = t.id,
                                      salesid = t.salesid,
                                      description = t.description,
                                      discount = t.discount,
                                      price = t.price,
                                      quantity = t.quantity,
                                      EmployeeName = e.firstname + " " + e.lastname,
                                      note = t.note

                                  }).ToList();

            detail.TicketTips = (from g in context.gratuities
                                 join e in context.employees
                                 on g.employeeid equals e.employeeid
                                 where e.userid == detail.userid && g.salesid == detail.id
                                 select new TicketGratuity
                                 {
                                     id = g.id,
                                     salesid = g.salesid,
                                     amount = g.amount,
                                     EmployeeName = e.firstname + " " + e.lastname

                                 }).ToList();
          

 
            return View(detail);
        }

        // GET: Sales/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sales/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Sales/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Sales/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Sales/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Sales/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebPortal/Views/Sales/Details.cshtml
@model WebAccess.ViewModels.Ticket

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Ticket #@(Model.ticketno)</h2>

<div>

    <dl class="dl-horizontal">


        <dt>
            Sale Date
        </dt>

        <dd>
            @Html.DisplayFor(model => model.saledate)
        </dd>


        <dt>
            Customer
        </dt>






        <dd>
            @Html.DisplayFor(model => model.customerid)
        </dd>

        <dt>
            SubTotal
        </dt>

        <dd>
            @Html.DisplayFor(model => model.subtotal)
        </dd>


        <dt>
            Adjustment
        </dt>

        <dd>
            @Html.DisplayFor(model => model.adjustment)
        </dd>



        <dt>
            Total
        </dt>

        <dd>
            @Html.DisplayFor(model => model.total)
        </dd>



        <dt>
            Note
        </dt>

        <dd>
            @Html.DisplayFor(model => model.note)
        </dd>

        <dt>
            Cashier
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.custom1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.custom1)
        </dd>
        <dt>
            Void Reason
        </dt>

        <dd>
            @Html.DisplayFor(model => model.custom4)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.stationno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.stationno)
        </dd>

    </dl>
</div>



<table class="table" style="width:400px">
    <tr>
        <th>
            Qty
        </th>
        <th>
            Description
        </th>
        <th>
            Price
        </th>
        <th>
            Discount
        </th>


        <th>
            Nail Tech
        </th>
        <th>
            Note
        </th>



    </tr>

    @foreach (var item in Model.TicketItems)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.quantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.price)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.discount)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.EmployeeName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.note)
        </td>




    </tr>
    }

</table>




<table class="table" style="width:300px">
    <tr>
        <th colspan="4">
            <b>PAYMENTS </b> 
        </th>


    </tr>

    @foreach (var item in Model.payments)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.authorcode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.netamount)
        </td>
        <td>
            @if (item.voided == 1)
    {
        <text>VOIDED</text>
}
else
{
        <text></text>
}
        </td>

    </tr>
    }

</table>

<table class="table" style="width:300px">
    <tr>
        <th colspan="2">
            <b>TIPS</b> 
       
        </th>


    </tr>

    @foreach (var item in Model.TicketTips)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EmployeeName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.amount)
            </td>


        </tr>
    }

</table>



<p>

    @Html.ActionLink("Back to List", "Index")
</p>

WebPortal/Views/Sales/Index.cshtml
@model IEnumerable<WebAccess.Models.sale>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script type="text/javascript" class="init">
    $(document).ready(function () {
        $('#table1').DataTable({ "bDestroy": "true", "scrollY": "500px", "lengthMenu": [[-1], ["All"]], "sDom": "tr" });

 
    });


    $(function () {


        $("#startdate").datepicker({
            showOn: "button",
            buttonImage: "/Content/calendar_small.gif",
            buttonImageOnly: true,
            buttonText: "Select date",
            autoclose: true
        });


        $("#enddate").datepicker({
            showOn: "button",
            buttonImage: "/Content/calendar_small.gif",
            buttonImageOnly: true,
            buttonText: "Select date",
            autoclose: true
        });

    })



    $('a.edit').click(function () {
        var url = $(this).attr('href');
        window.open(url, "popupWindow", "width=900,height=600,scrollbars=yes");
        return false;
    });
</script>

<ul class="breadcrumb">
    <li><a href="\Home">Home</a></li>
    <li class="active">Sales</li>
</ul>


<h2>Tickets</h2>

@{
    decimal total = 0;



}


<p>
    @using (Html.BeginForm("Index", "Sales"))
    {



        <div class="row">
            <div class="col-sm-2 ">
                <div class="input-group">
                    <span class="input-group-addon">Store:</span>
                    @Html.DropDownList("StoreId", (IEnumerable<SelectListItem>)ViewBag.Stores, htmlAttributes: new { @class = "form-control" })
                </div>


            </div>
            <div class="col-sm-3 ">
                <div class="input-group">
                    <span class="input-group-addon">Start Date:</span>
                    @Html.TextBox("startdate", (string)ViewBag.startdate, new { @class = "form-control", placeholder = "MM/DD/YYYY" })
                </div>


            </div>
            <div class="col-sm-3 ">
                <div class="input-group">
                    <span class="input-group-addon">End Date:</span>
                    @Html.TextBox("enddate", (string)ViewBag.enddate, new { @class = "form-control", placeholder = "MM/DD/YYYY" })
                </div>


            </div>

            <div class="col-sm-1">
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="submit" class="btn btn-primary" name="action" value="save" id="action" data-toggle="tooltip" data-placement="right" title="Refresh Data">Refresh</button>
                    </div>
                </div>
            </div>

        </div>




    }

</p>


<table class="display" id="table1" style="width: 500px">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.ticketno)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.saledate)
            </th>
  

            <th>
                @Html.DisplayNameFor(model => model.total)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.note)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.status)
            </th>



            <th> Details</th>
            <th>Payments</th>
            <th>Tips</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            total = total + (decimal)item.total;
 
   
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.ticketno)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.saledate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.employeeid)
            </td>


            <td>
                @Html.DisplayFor(modelItem => item.total)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.note)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.status)
            </td>


            <td>


                <table class="table" style="width:400px">
                    <tr>
                        <th>
                            Qty
                        </th>
                        <th>
                            Description
                        </th>
                        <th>
                            Price
                        </th>
                        <th>
                            Discount
                        </th>


                        <th>
                            Nail Tech
                        </th>
                        <th>
                            Note
                        </th>



                    </tr>

                    @foreach (var item2 in item.salesitems)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item2.quantity)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item2.description)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item2.price)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item2.discount)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item2.employeeid)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item2.note)
                            </td>




                        </tr>
                    }

                </table>

    
            </td>

            <td>

                <table class="table" style="width:300px">
                    <tr>
                        <th colspan="4">
                            <b>PAYMENTS </b>
                        </th>


                    </tr>

                    @foreach (var item2 in item.payments)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item2.description)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item2.authorcode)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item2.netamount)
                            </td>
                            <td>
                                @if (item2.voided == 1)
                                {
                                    <text>VOIDED</text>
                                }
                                else
                                {
                                    <text></text>
                                }
                            </td>

                        </tr>
                    }

                </table>
            </td>

            <td>

                <table class="table" style="width:300px">
                    <tr>
                        <th colspan="2">
                            <b>TIPS</b>

                        </th>


                    </tr>
   
                    @foreach (var item2 in item.gratuities)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item2.employeeid)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item2.amount)
                            </td>


                        </tr>
                    }

                </table>
            </td>
            <td>
         

                @Html.ActionLink("Details", "Details", "Sales", new { id = item.id }, new { @class = "btn btn-success", target = "popup", onclick = "window.open('../Sales/Details?id=" + item.id + "','popup','width=1000,height=1000'); return false;" })


            </td>
        </tr>
        }

    </tbody>







    <tfoot>
        <tr>

            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>

            <td>
                &nbsp;
            </td>

            <td>
                &nbsp;
            </td>

            <td>
                @(total)
            </td>

            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
    </tfoot>


</table>