WebPortal/Controllers/PermissionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAccess.Models;

namespace WebAccess.Controllers
{
    public class PermissionController : BaseController
    {
        webaccessEntities context;

        public PermissionController()
        {
            context = new webaccessEntities();

        }
        // GET: Permission
        public ActionResult Index(string id)
        {
            try
            {
                if (id == null) return RedirectToAction("index", "home");

                //only select items that is not already on user permission list
                var contained = context.AspNetUserRoles.Where(x => x.UserId == id).Select(x => x.AspNetRole.Name).ToList();
                ViewBag.Roles = new SelectList(context.AspNetRoles.Where(y => !contained.Contains(y.Name)).ToList(), "Id", "Name");
                ViewBag.UserId = id;


                return View(context.AspNetUsers.Find(id));

            }catch(Exception ex)
            {
                return RedirectToAction("index", "error", ex);
            }
           
        }



        [HttpPost]
        public ActionResult Index(string Id, List<AspNetUserRole> AspNetUserRoles)
        {
            //Id = User Id ( GUID = unique string id)
            foreach (AspNetUserRole userrole in AspNetUserRoles)
            {
                var current = context.AspNetUserRoles.Where(x => x.UserId == Id).Where(x => x.RoleId == userrole.RoleId).First();
                current.C = userrole.C;
                current.R = userrole.R;
                current.U = userrole.U;
                current.D = userrole.D;
                current.A = userrole.A;
            }

            context.SaveChanges();

            TempData["UserMessage"] = new UserMessage { CssClassName = "alert-success", Title = "Success!", Message = "Data Saved." };
         
            return RedirectToAction("Index","Users",null);
        }

   

        // POST: Permission/Create
        [HttpPost]
        public ActionResult Create(string id, string RoleId)
        {
            try
            {
                if(RoleId!=null)
                {
                    AspNetUserRole collection = new AspNetUserRole();
                    collection.UserId = id;
                    collection.RoleId = RoleId;
                    collection.R = true;
                    context.AspNetUserRoles.Add(collection);
                    context.SaveChanges();
                }

                TempData["UserMessage"] = new UserMessage { CssClassName = "alert-success", Title = "Success!", Message = "New Record Created." };
                return RedirectToAction("Index", new {id= id });
            }
            catch(Exception ex)
            {
                return RedirectToAction("index", "error", ex);
            }
        }





        // GET: Permission/Delete/5
       
        public ActionResult Delete(string UserId, string RoleId)
        {
           // return View(context.AspNetUserRoles.Find(UserId, RoleId));
            return View(context.AspNetUserRoles.Where(x=>x.UserId == UserId).Where(y=>y.RoleId == RoleId).First());
        }

        // POST: Permission/Delete/5
        [HttpPost]
        public ActionResult Delete(int? UserId, AspNetUserRole collection)
        {
            try
            {
                // TODO: Add delete logic here
                var deletetarget = context.AspNetUserRoles.Where(x => x.UserId == collection.UserId).Where(y => y.RoleId == collection.RoleId).First();
                context.AspNetUserRoles.Remove(deletetarget);
                context.SaveChanges();
                TempData["UserMessage"] = new UserMessage { CssClassName = "alert-success", Title = "Success!", Message = "Record Deleted." };
                return RedirectToAction("Index", new { id = collection.UserId });
            }
            catch
            {
                return View(context.AspNetUserRoles.Where(x => x.UserId == collection.UserId).Where(y => y.RoleId == collection.RoleId).First());
            }
        }
    }
}

WebPortal/Views/Permission/Create.cshtml
@model WebAccess.Models.AspNetUserRole

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create New Permission</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Hidden("UserId", (string)ViewBag.UserId)

        <div class="form-group">
            @Html.Label("Page / Action", "RoleId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RoleId", (IEnumerable<SelectListItem>)ViewBag.Roles, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RoleId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Create", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.C)
                    @Html.ValidationMessageFor(model => model.C, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Read", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.R)
                    @Html.ValidationMessageFor(model => model.R, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Update", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.U)
                    @Html.ValidationMessageFor(model => model.U, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Delete", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.D)
                    @Html.ValidationMessageFor(model => model.D, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Approve", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.A)
                    @Html.ValidationMessageFor(model => model.A, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create New Permission Set" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { id = (string)ViewBag.UserId })
</div>

WebPortal/Views/Permission/Delete.cshtml
@model WebAccess.Models.AspNetUserRole

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Remove Permission from @Model.AspNetUser.FirstName</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Permission to be removed: </h4>
 
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.C)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.C)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.R)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.R)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.U)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.U)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.D)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.D)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.A)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.A)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetRole.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetRole.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.FirstName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        
        
        @Html.AntiForgeryToken()
      
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to Permission List", "Index", new { id = Model.UserId })
        </div>
    }
</div>

WebPortal/Views/Permission/Index.cshtml
@model WebAccess.Models.AspNetUser
@{
    ViewBag.Title = "Assign Permission";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ul class="breadcrumb">
    <li><a href="\Home">Home</a></li>
    <li><a href="\Users">Users</a></li>
 
    <li class="active">Permissions</li>
</ul>

<h3>Assign Permission for  @Html.DisplayFor(modelItem => Model.FirstName) @Html.DisplayFor(modelItem => Model.LastName)</h3>
<br />


@using (Html.BeginForm("Create", "Permission", FormMethod.Post))
{
    @Html.Hidden("Id", Model.Id)
    <div class="row">
       
        <div class="col-sm-2">
            @Html.DropDownList("RoleId", (IEnumerable<SelectListItem>)ViewBag.Roles, htmlAttributes: new { @class = "form-control" })
        
        </div>

        <div class="col-sm-1 col-sm-offset-1">
            <input type="submit" value="Assign to User" class="btn btn-primary" />
        </div>
    </div>

}

<br />

@using (Html.BeginForm("Index", "Permission", FormMethod.Post))
{

    @Html.Hidden("Id",Model.Id)

    <table class="table">
        <tr>
            <th>
                @VTTLanguages.Resources.ProgramAreaAccess
            </th>
            <th>
               @VTTLanguages.Resources.Create
            </th>
            <th>
                @VTTLanguages.Resources.Read
            </th>
            <th>
                @VTTLanguages.Resources.Update
            </th>
            <th>
                @VTTLanguages.Resources.Delete
            </th>
            <th>
                @VTTLanguages.Resources.Approve
            </th>


            <th></th>
        </tr>

        @{ int i = 0;
           foreach (var item in Model.AspNetUserRoles)
           {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.AspNetRole.Name)
                    @Html.Hidden("AspNetUserRoles[" + @i + "].RoleId", item.AspNetRole.Id)
                </td>
                <td>
                    <div class="form-group">

                        <div class="col-md-10">
                            @Html.CheckBox("AspNetUserRoles[" + @i + "].C", item.C)
                            @Html.ValidationMessageFor(modelItem => item.C, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
                <td>
                    <div class="form-group">

                        <div class="col-md-10">
                            @Html.CheckBox("nada", item.R, new {disabled="disabled" })
                            @Html.Hidden("AspNetUserRoles[" + @i + "].R", item.R)
                          
                        </div>
                    </div>
                </td>
                <td>
                    <div class="form-group">

                        <div class="col-md-10">
                            @Html.CheckBox("AspNetUserRoles[" + @i + "].U", item.U)
                            @Html.ValidationMessageFor(modelItem => item.U, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
                <td>
                    <div class="form-group">

                        <div class="col-md-10">
                            @Html.CheckBox("AspNetUserRoles[" + @i + "].D", item.D)
                            @Html.ValidationMessageFor(modelItem => item.D, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
                <td>
                    <div class="form-group">

                        <div class="col-md-10">
                            @Html.CheckBox("AspNetUserRoles[" + @i + "].A", item.A)
                            @Html.ValidationMessageFor(modelItem => item.A, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>


                <td>
                    @Html.ActionLink(@VTTLanguages.Resources.Remove, "Delete", new { UserId = item.UserId, RoleId = item.RoleId })
                </td>
            </tr>
           i = i + 1;
        }}

        <tr>
            <td colspan="7">
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save and Close" class="btn btn-primary" />
                    </div>
                </div>
            </td>
        </tr>
    </table>
}